pull_request_rules:
  - name: automatic rebase for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build
      - check-success=Vercel
    actions:
      merge:
        method: rebase
